import angular              from 'angular'
import uiRouter             from 'angular-ui-router'
import uiBootstrap          from 'angular-ui-bootstrap'
import environment          from 'angular-environment'
import ngMask               from 'ng-mask'
import ngMessages           from 'angular-messages'
import ngSanitize           from 'textangular/dist/textAngular-sanitize'
import textAngular          from 'textangular'
import ngLocale             from 'angular-i18n/pt-br'
import                           'ng-img-crop/compile/unminified/ng-img-crop.js'
